# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxNetworkDemo' do

pod 'RxSwift', '~>5'
pod 'RxCocoa', '~>5'
pod 'Alamofire', :git => ‘https://github.com/Alamofire/Alamofire.git', :branch => ‘alamofire5’
pod 'SwiftyJSON', '~>5'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxNetworkDemo

end
